config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'home#index'

  get '/:year/:month/:day/:slug' => 'articles#show', as: :show_article
  get '/about' => 'about#index', as: :about
  get '/portfolio' => 'portfolio#index', as: :portfolio
  get '/publications' => 'publications#index', as: :publications
  get '/contacts' => 'contacts#index', as: :contacts

  get 'rss.xml' => 'home#feed', :defaults => { :format => 'rss' }, as: :feed

end

app/models/ability.rb
# Permission cancan
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :access, :rails_admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/about.rb
# About model
class About < ActiveRecord::Base
  include DateHelper

  validates :title, :body, presence: true
  mount_uploader :image, AboutUploader
end

app/models/article.rb
# Article model
class Article < ActiveRecord::Base
  include DateHelper
  include Rails.application.routes.url_helpers

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :summary, :date_publish, :body, presence: true

  has_and_belongs_to_many :categories
  has_many :article_attachments, dependent: :destroy

  accepts_nested_attributes_for :article_attachments, allow_destroy: true

  def markdown
    options = {
      fenced_code_blocks: true, no_intra_emphasis: true, lax_html_blocks: true
    }

    extensions = {
      autolink: true, superscript: true, highlight: true,
      footnotes: true, disable_indented_code_blocks: false
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(body).html_safe
  end

  def link_article
    date = date_publish

    link = show_article_path(
      year: date.year,
      month: date.strftime('%m'),
      day: date.strftime('%d'),
      slug: slug
    ) << '/'

    link
  end
end

app/models/article_attachment.rb
# Attachemnts model
class ArticleAttachment < ActiveRecord::Base
  validates :title, :image, presence: true

  mount_uploader :image, ImageUploader
end

app/models/category.rb
# Category model
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true

  has_and_belongs_to_many :articles
end

app/models/contact.rb
# Model contact
class Contact < ActiveRecord::Base
  validates :title, :link, presence: true
end

app/models/portfolio.rb
# Model Portfolio
class Portfolio < ActiveRecord::Base
  include DateHelper

  validates :title, :link, presence: true
end

app/models/publication.rb
# Model publication
class Publication < ActiveRecord::Base
  include DateHelper

  validates :title, :date_publish, :description, :arquive, presence: true
  mount_uploader :arquive, ArquiveUploader
end

app/models/user.rb
# Model user to Devise
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
# Controller about
class AboutController < ApplicationController
  def index
    @about = About.first

    @title = 'Luiz Picolo - Quem sou'
    @description = 'Saiba um poco mais sobre Luiz Picolo'
  end
end

app/controllers/application_controller.rb
# First controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
# Article controller
class ArticlesController < ApplicationController
  def show
    @article = Article.find_by_slug(params[:slug])

    @gravatar = Gravatar.new('luizpicolo@gmail.com').image_url

    @title = @article.title
    @description = @article.summary.first(255)
  end
end

app/controllers/contacts_controller.rb
# Contact controller
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
    @title = 'Luiz Picolo - Contatos'
    @description = 'Entre em contato comigo. Seus comentários e sugestões são
                    muito importantes. No momento não atuo mais como freelancer
                    e não tenho disponibilidade para novos trabalhos.
                    Se você é desenvolvedor Ruby ou PHP iniciante e está
                    procurando informações sobre trabalho e carreira, acesse
                    meu blog, é lá onde eu publico todas as dicas
                    sobre o assunto. E se você quiser pode falar comigo no
                    contato luizpicolo@gmail.com, mas já aviso que não respondo
                    nada que você possa encontrar sozinho no meu blog ou no
                    Google =)'.first(255)
  end
end

app/controllers/home_controller.rb
# Home Controller
class HomeController < ApplicationController
  def index
    @description = 'Site sobre desenvolvimento web mantido por Luiz Picolo.'
    @description << 'Para mais detalhes veja http://luizpicolo.com.br/about'

    @articles = Article.order('date_publish desc').page(params[:page])
  end

  def feed
    @articles = Article.all
  end
end

app/controllers/portfolio_controller.rb
# Portfolio Controller
class PortfolioController < ApplicationController
  def index
    @portfolio = Portfolio.all

    @title = 'Luiz Picolo - Portfolio'
    @description = 'O portfolio de um programador, na minha opinião,
                    não deve ser exatamente o produto final dos projetos
                    que o mesmo participou, mas sim o código criado pelo mesmo.
                    Por este motivo, nesta página, estou disponibilizando grande
                    parte dos projetos executados nas linguagem que trabalho.'
  end
end

app/controllers/publications_controller.rb
# Publication controller
class PublicationsController < ApplicationController
  def index
    @publications = Publication.all

    @title = 'Luiz Picolo - Publicações'
    @description = 'Aqui você pode encontrar algumas publicações de Luiz Picolo
                    publicadas em eventos, site, entre outros'
  end
end

app/helpers/application_helper.rb
# Module App helper
module ApplicationHelper
end

app/helpers/date_helper.rb
# Module DateHelper
module DateHelper
  def updated_in
    format_date updated_at
  end

  def published_in
    format_date date_publish
  end

  private

  def format_date(dt)
    month = I18n.t('date.month_names')[dt.mon]
    day = dt.mday.to_s
    year = dt.year.to_s

    day << ' de ' << month << ' de ' << year
  end
end

app/views/about/index.html.erb
<article class="articles">
  <h1 class="title-3"><%= t("about") %></h1>
  <div class="publish_date">
    <%= t("updated_in")%>: <time datetime="<%= @about.updated_at %>"> <%= @about.updated_in %></time>
  </div>
  <% unless @about.image_url.nil? %>
  <figure class="image-left">
    <%= image_tag @about.image_url("thumb") %>
    <figcaption></figcaption>
  </figure>
  <% end %>
  <p class="text-justif">
    <%= @about.body.html_safe %>
  </p>
</article>

app/views/articles/show.html.erb
<article class="articles">
  <h1><%= @article.title %></h1>
  <div class="publish_date">
    <%= t("published_in")%>: <time datetime="<%= @article.date_publish %>"> <%= @article.published_in %></time>
  </div>
  <% @article.article_attachments.where(:hightlight => false).find_each do |image| %>
  <figure>
    <%= image_tag image.image_url(:hightlight), :class => "img-responsive" %>
    <figcaption><%= image.title %></figcaption>
  </figure>
  <% end %>
  <p>
    <%= @article.markdown %>
  </p>
  <%= link_to :back, :class => "read-more" do %>
    <i class="fa fa-long-arrow-left"></i>
    <%= t("back") %>
  <% end %>
</article>

<div class="authors">
  <div class="about-author">
    <%= image_tag @gravatar, :class => "gravatar" %>
    <div class="info">
      <p class="name">Luiz Picolo</p>
      <p class="job">Desenvolvedor Web</p>
      <p class="social">
        <a target="_blank" title="GitHub" href="https://github.com/luizpicolo"><i class="fa fa-github-square"></i></a>
        <a target="_blank" title="Twitter" href="https://twitter.com/luizpicolo_"><i class="fa fa-twitter-square"></i></a>
        <a target="_blank" title="Twitter" href="https://www.fb.com/luizpicolo"><i class="fa fa-facebook-square"></i></a>
      </p>
    </div>
  </div>
</div>

<div id="disqus_thread"></div>
<script>
    (function() {
        var d = document, s = d.createElement('script');
        s.src = '//luizpicolo.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<br />

app/views/contacts/index.html.erb
<article class="articles">
  <h1 class="title-3"><%= t("contact") %></h1>
  <p class="text-justif">
    Entre em contato comigo. Seus comentários e sugestões são muito importantes.
No momento não atuo mais como freelancer e não tenho disponibilidade para novos trabalhos.
Se você é desenvolvedor Ruby ou PHP iniciante e está procurando informações sobre trabalho e carreira, acesse meu blog, é lá onde eu publico todas as dicas sobre o assunto. E se você quiser pode falar comigo no contato luizpicolo@gmail.com, mas já aviso que não respondo nada que você possa encontrar sozinho no meu blog ou no Google =)
  </p>
  <% @contacts.each do |contact| %>
    <h2 class="title-1"><%= contact.title%></h2>
    <%= link_to contact.link, contact.link, :class => "read-more"%>
  <% end %>
</article>

app/views/home/index.html.erb
<% @articles.each do |article| %>
<article class="articles">
  <%= link_to article.link_article, :class => "title-link" do %>
  <h1><%= article.title %></h1>
  <% end %>
  <div class="publish_date">
    <%= t("published_in")%>: <time datetime="<%= article.date_publish %>"> <%= article.published_in %></time>
  </div>
  <% article.article_attachments.where(:hightlight => true).find_each do |image| %>
  <figure>
    <%= image_tag image.image_url(:hightlight), :width => "100%", :class => "img-responsive" %>
    <figcaption><%= image.title %></figcaption>
  </figure>
  <% end %>
  <p>
    <%= article.summary.html_safe %>
  </p>
  <%= link_to article.link_article, :class => "read-more" do %>
    <%= t("read_more") %>
    <i class="fa fa-long-arrow-right"></i>
  <% end %>
</article>
<% end %>

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
	<%
		if key != 'success' && key != 'danger' && key != 'notice'
			key = 'danger'
		end
	%>
    <div class="alert-message alert-message-<%= key %>">
      <button type="button" class="close">&times;</button>
      <%= value.html_safe %>
    </div>
<% end %>

app/views/layouts/_head_devise.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<title>Área Administrativa - Agência W3Case</title>

	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<%= favicon_link_tag 'w3case-icon.png' %>
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag :modernizr %>
</head>

app/views/layouts/_links.html.erb
<ul>
  <li><%= link_to t("contact"), contacts_path %></li>
  <li><%= link_to t("publications"), publications_path %></li>
  <li><%= link_to t("screencast"), "#" %></li>
  <li><%= link_to t("portfolio"), portfolio_path %></li>
  <li><%= link_to t("about"), about_path %></li>
  <li><%= link_to t("home"), root_path %></li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="pt-br">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="blitz" content="mu-53238a8b-3f5ac272-16a393b6-e4f60509">
	<%= csrf_meta_tags %>

	<title>Luiz Picolo - <%= @title or "Desenvolvimento Web" %></title>

	<%= favicon_link_tag 'icon.png' %>

	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'modernizr' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<!-- start marketizator.com code -->
	<link rel="dns-prefetch" href="//app.marketizator.com"/>
	<script type="text/javascript" src="//d2tgfbvjf3q6hn.cloudfront.net/js/bc1e06.js"></script>
	<!-- end marketizator.com code -->
</head>

<body>
	<%= render "layouts/alerts" %>
	<header id="header" class="clearfix">
		<div class="col-sm-3">
			<hgroup>
				<%= link_to root_path do %>
				<h1><strong>Luiz</strong> Picolo</h1>
				<h2><%= t("web_development")%></h2>
				<% end %>
			</hgroup>
		</div>
		<div class="col-sm-9">
			<nav id="nav">
				<%= render "layouts/links" %>
			</nav>
		</div>
	</header>

	<main id="main">
		<%= yield %>
	</main>

	<footer id="footer">
		<div class="row">
			<div class="col-sm-5 align-link">
				<div class="title-1">
					<%= t("pages") %>
				</div>
				<%= render "layouts/links" %>
			</div>
			<div class="col-sm-5 align-link">
				<div class="title-1">
					<%= t("follow_me")%>
				</div>
				<ul>
					<% cache do %>
						<% Contact.order("title asc").each do |contact|%>
							<li><%= link_to contact.title, contact.link %></li>
						<% end %>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="text-center row margin-top margin-bottom title-2">
			Criado com <i class='fa fa-heart'></i> por Luiz Picolo
		</div>
	</footer>

	<div class="social-links">
		<%= link_to "http://www.github.com/luizpicolo", :target => "blank" do %>
		<i class="fa fa-github" data-toggle="tooltip" data-placement="right" title="Github"></i>
		<% end %>
		<%= link_to "http://www.twitter.com/luizpicolo_", :target => "blank" do %>
		<i class="fa fa-twitter" data-toggle="tooltip" data-placement="right" title="Twitter"></i>
		<% end %>
		<%= link_to "http://www.facebook.com.br/luizpicolo", :target => "blank" do %>
		<i class="fa fa-facebook" data-toggle="tooltip" data-placement="right" title="Facebook"></i>
		<% end %>
		<%= link_to feed_path, :target => "blank" do %>
		<i class="fa fa-rss" data-toggle="tooltip" data-placement="right" title="Feed"></i>
		<% end %>
	</div>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-21765459-1', 'auto');
	  ga('send', 'pageview');
	</script>
</body>
</html>

app/views/portfolio/index.html.erb
<article class="articles">
  <h1 class="title-3"><%= t("portfolio") %></h1>
  <div class="publish_date">
    <%= t("updated_in")%>: <time datetime="<%= @portfolio.last.updated_at %>"> <%= @portfolio.last.updated_in %></time>
  </div>
  <p class="text-justif">
    O portfolio de um programador, na minha opinião, não deve ser exatamente o produto final dos projetos que o mesmo participou, mas sim o código criado pelo mesmo. Por este motivo, nesta página, estou disponibilizando grande parte dos projetos executados nas linguagem que trabalho.
  </p>
  <% @portfolio.each do |work| %>
    <h2 class="title-1"><%= work.title%></h2>
    <%= link_to work.link, work.link, :class => "read-more"%>
  <% end %>
</article>

app/views/publications/index.html.erb
<articles class="articles">
  <h1><%= t('publications') %></h1>
  <div class="publish_date">
    <%= t("updated_in")%><time datetime="<%= @publications.last.updated_at %>"> <%= @publications.last.updated_in %></time>
  </div>
</articles>
<% @publications.each do |publication| %>
<articles class="articles">
  <h2 class="title-3"><%= publication.title%></h2>
  <p>
    <%= publication.description.html_safe %>
  </p>
  <p><%= link_to t('original_version'), publication.arquive_url %></p>
</articles>
<hr>
<% end %>